"""Write audit results as JSON, CSV, Markdown, or a self-contained HTML report."""

from __future__ import annotations

import csv
import io
import json
from html import escape

from .checks import FAIL, NOT_APPLICABLE, NOT_ASSESSED, PASS
from .engine import AuditResult

DISCLAIMER = (
    "This report is generated by an automated audit aid from the account data supplied. It does not "
    "replace a formal assessment or the judgment of a qualified auditor. Zero Trust Maturity Model "
    "stages are indicative estimates for the Identity pillar based on account data only."
)
STATUS_TEXT = {PASS: "Pass", FAIL: "Fail", NOT_ASSESSED: "Not assessed", NOT_APPLICABLE: "Not applicable"}


def _pct(v: float | None) -> str:
    return "n/a" if v is None else f"{v:.0f}%"


def grouped_findings(result: AuditResult) -> list[dict]:
    """Findings grouped by check, in priority order, with the affected accounts listed."""
    groups: dict[str, dict] = {}
    for f in result.findings:
        g = groups.setdefault(f.rule_id, {"finding": f, "accounts": [], "details": []})
        if f.account:
            g["accounts"].append(f.account)
            g["details"].append(f"{f.account}: {f.detail}")
        else:
            g["details"].append(f.detail)
    return list(groups.values())


def to_json(result: AuditResult) -> str:
    return json.dumps(result.to_dict(), indent=2, default=str)


def to_csv(result: AuditResult) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["account", "account_type", "rule_id", "title", "severity", "controls",
                "ztmm_function", "detail", "remediation"])
    for f in result.findings:
        w.writerow([f.account or "(organization)", f.account_type or "", f.rule_id, f.title, f.severity,
                    "; ".join(f.controls), f.ztmm_function, f.detail, f.remediation])
    return buf.getvalue()


def to_markdown(result: AuditResult) -> str:
    m = result.metrics
    lines = [
        f"# Zero Trust identity audit: {result.organization}",
        "",
        f"NIST SP 800-53 {result.baseline} baseline | Generated {result.generated_at}",
        "",
        f"- Weighted identity risk exposure: **{result.risk_score:.1f} / 100 ({result.risk_rating})**",
        f"- MFA coverage of enabled human accounts: **{_pct(m['mfa_coverage_pct'])}**",
        f"- Privileged human accounts with phishing-resistant MFA: **{_pct(m['privileged_phishing_resistant_pct'])}**",
        f"- Accounts: {m['accounts_enabled']} enabled of {m['accounts_total']}, "
        f"{m['accounts_privileged']} privileged, {m['accounts_service']} service, {m['accounts_guest']} guest",
        f"- Accounts with critical or high findings: **{m['accounts_high_risk']}**",
        "",
        "## Zero Trust Maturity Model, Identity pillar (indicative)",
        "",
        "| Function | Estimated stage | Basis |",
        "|---|---|---|",
    ]
    lines += [f"| {z.function} | {z.stage} | {z.basis} |" for z in result.ztmm]
    lines += ["", "## Findings by priority", ""]
    groups = grouped_findings(result)
    if not groups:
        lines.append("No findings.")
    for g in groups:
        f = g["finding"]
        lines += [f"### [{f.severity.upper()}] {f.rule_id}: {f.title}",
                  f"Controls: {', '.join(f.controls)} | ZTMM function: {f.ztmm_function}  "]
        lines += [f"- {d}" for d in g["details"]]
        lines += ["", f"Remediation: {f.remediation}", ""]
    lines += ["## All checks", "", "| Check | Title | Severity | Result | In scope | Failed | Not assessed |",
              "|---|---|---|---|---|---|---|"]
    for s in result.rules:
        lines.append(f"| {s.rule_id} | {s.title} | {s.severity.title()} | {STATUS_TEXT[s.status]} | "
                     f"{s.in_scope} | {s.failed} | {s.not_assessed} |")
    lines += ["", f"_{DISCLAIMER}_", ""]
    return "\n".join(lines)


_CSS = """
:root{--ink:#1d2939;--muted:#5b6675;--line:#d5dae0;--paper:#fff;--wash:#f5f7f9;
--fail:#b42318;--pass:#1e7b4f;--partial:#a15c07;--na:#5b6675}
*{box-sizing:border-box}
body{margin:0;background:var(--wash);color:var(--ink);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
main{max-width:980px;margin:0 auto;padding:40px 24px 64px;background:var(--paper)}
h1,h2,h3{font-family:Charter,"Bitstream Charter","Iowan Old Style",Georgia,serif;line-height:1.25}
h1{font-size:30px;margin:0 0 6px}
h2{font-size:21px;margin:44px 0 12px;padding-bottom:6px;border-bottom:2px solid var(--ink)}
h3{font-size:16px;margin:0 0 6px}
.meta{color:var(--muted);margin:0}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));margin-top:28px;border:1px solid var(--line)}
.summary div{padding:16px 18px;border-right:1px solid var(--line)}
.summary div:last-child{border-right:0}
.figure{font-family:Charter,Georgia,serif;font-size:34px;font-weight:700;display:block}
.label{color:var(--muted);font-size:13px}
.finding{border-left:4px solid var(--fail);padding:12px 16px;margin:14px 0;background:var(--wash)}
.finding.medium{border-left-color:var(--partial)}.finding.low{border-left-color:var(--na)}
.finding p{margin:4px 0}.finding ul{margin:6px 0 6px 18px;padding:0}
.sev{display:inline-block;font-size:12px;font-weight:700;padding:1px 8px;border-radius:3px;color:#fff;background:var(--fail);margin-right:6px}
.sev.medium{background:var(--partial)}.sev.low{background:var(--na)}
.table-wrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:14px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{font-weight:600;color:var(--muted)}
.s-Pass,.s-Advanced,.s-Optimal{color:var(--pass);font-weight:600}
.s-Fail,.s-Traditional{color:var(--fail);font-weight:600}
.s-Initial{color:var(--partial);font-weight:600}
.s-Not-assessed,.s-Not-applicable{color:var(--na)}
.disclaimer{margin-top:40px;color:var(--muted);font-size:13px}
@media print{body{background:#fff}main{padding:0}}
"""


def _cls(text: str) -> str:
    return "s-" + text.replace(" ", "-")


def to_html(result: AuditResult) -> str:
    e = escape
    m = result.metrics
    cards = []
    for g in grouped_findings(result):
        f = g["finding"]
        sev = f.severity if f.severity in ("medium", "low") else ""
        items = "".join(f"<li>{e(d)}</li>" for d in g["details"])
        cards.append(
            f'<div class="finding {sev}"><h3><span class="sev {sev}">{e(f.severity.title())}</span>'
            f'{e(f.rule_id)}: {e(f.title)}</h3>'
            f'<p><strong>Controls:</strong> {e(", ".join(f.controls))}. '
            f'<strong>ZTMM function:</strong> {e(f.ztmm_function)}.</p><ul>{items}</ul>'
            f'<p><strong>Remediation:</strong> {e(f.remediation)}</p></div>')
    if not cards:
        cards.append("<p>No findings.</p>")
    ztmm_rows = "".join(f'<tr><td>{e(z.function)}</td><td class="{_cls(z.stage)}">{e(z.stage)}</td>'
                        f'<td>{e(z.basis)}</td></tr>' for z in result.ztmm)
    by_acct = result.findings_by_account()
    acct_rows = "".join(
        f"<tr><td>{e(a)}</td><td>{e(fs[0].account_type or '')}</td>"
        f"<td>{e(', '.join(sorted({f.severity.title() for f in fs}, key=['Critical','High','Medium','Low'].index)))}</td>"
        f"<td>{e('; '.join(f.title for f in fs))}</td></tr>"
        for a, fs in by_acct.items())
    rule_rows = "".join(
        f'<tr><td>{e(s.rule_id)}</td><td>{e(s.title)}</td><td>{e(", ".join(s.controls))}</td>'
        f'<td>{e(s.severity.title())}</td><td class="{_cls(STATUS_TEXT[s.status])}">{STATUS_TEXT[s.status]}</td>'
        f'<td>{s.failed} of {s.in_scope}</td></tr>' for s in result.rules)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Zero Trust identity audit: {e(result.organization)}</title>
<style>{_CSS}</style></head>
<body><main>
<h1>Zero Trust identity audit: {e(result.organization)}</h1>
<p class="meta">NIST SP 800-53 {e(result.baseline)} baseline. {m['accounts_total']} accounts reviewed. Generated {e(result.generated_at)} by iam_audit {e(result.tool_version)}.</p>
<section class="summary" aria-label="Summary">
<div><span class="figure">{result.risk_score:.1f}<small style="font-size:16px"> / 100</small></span><span class="label">Identity risk exposure ({e(result.risk_rating)})</span></div>
<div><span class="figure">{_pct(m['mfa_coverage_pct'])}</span><span class="label">MFA coverage, enabled human accounts</span></div>
<div><span class="figure">{_pct(m['privileged_phishing_resistant_pct'])}</span><span class="label">Admins with phishing-resistant MFA</span></div>
<div><span class="figure">{m['accounts_high_risk']}</span><span class="label">Accounts with critical or high findings</span></div>
</section>
<h2>Zero Trust Maturity Model: Identity pillar</h2>
<div class="table-wrap"><table><thead><tr><th>Function</th><th>Estimated stage</th><th>Basis</th></tr></thead><tbody>{ztmm_rows}</tbody></table></div>
<h2>Findings by priority</h2>
{''.join(cards)}
<h2>Accounts needing action</h2>
<div class="table-wrap"><table><thead><tr><th>Account</th><th>Type</th><th>Severity</th><th>Issues</th></tr></thead><tbody>{acct_rows}</tbody></table></div>
<h2>All checks</h2>
<div class="table-wrap"><table><thead><tr><th>Check</th><th>Title</th><th>Controls</th><th>Severity</th><th>Result</th><th>Failing</th></tr></thead><tbody>{rule_rows}</tbody></table></div>
<p class="disclaimer">{e(DISCLAIMER)}</p>
</main></body></html>
"""


WRITERS = {"json": to_json, "csv": to_csv, "md": to_markdown, "html": to_html}
